### PR TITLE
Feature decidim calendar

### PR DESCRIPTION
**Pull request by mijailr**
This add decidim-calendar functionalities.

imagen

### CODE REVIEW

**Comment by jkraemer** [comment]
I just tried it out - it appears to work in dev mode but with eager loading / class caching enabled (production) it fails to start:

~~~~
         5: from /home/jk/.gem/ruby/2.5.1/gems/activesupport-5.2.1.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
         4: from /home/jk/.gem/ruby/2.5.1/gems/activesupport-5.2.1.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
         3: from /home/jk/.gem/ruby/2.5.1/gems/activesupport-5.2.1.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
         2: from /home/jk/.gem/ruby/2.5.1/bundler/gems/decidim-module-calendar-dbe8d873c9e1/app/services/decidim/calendar/meeting_to_event.rb:3:in `<top (required)>'
         1: from /home/jk/.gem/ruby/2.5.1/bundler/gems/decidim-module-calendar-dbe8d873c9e1/app/services/decidim/calendar/meeting_to_event.rb:4:in `<module:Decidim>'
/home/jk/.gem/ruby/2.5.1/bundler/gems/decidim-module-calendar-dbe8d873c9e1/app/services/decidim/calendar/meeting_to_event.rb:5:in `<module:Calendar>': uninitialized constant Decidim::Meetings::Calendar::MeetingToEvent (NameError)
~~~~

**Comment by mijailr** [comment]
Sorry for that, now should work. Tested in production environment with this repository.

**Comment by jkraemer** [comment]
thanks, that works now, however with the staging DB I now run into an error when clicking the Calendar link in the main menu which is apparently caused by some event having either no start or end date:

~~~~
[9cf7ff7b-b89a-4078-b020-7f2839402eca] ActionView::Template::Error (undefined method `strftime' for nil:NilClass):
[9cf7ff7b-b89a-4078-b020-7f2839402eca]     36:        hour12: false,
[9cf7ff7b-b89a-4078-b020-7f2839402eca]     37:        omitZeroMinute: false
[9cf7ff7b-b89a-4078-b020-7f2839402eca]     38:      },
[9cf7ff7b-b89a-4078-b020-7f2839402eca]     39:      events: <%= render_events(@events).html_safe %>,
[9cf7ff7b-b89a-4078-b020-7f2839402eca]     40:      eventRender: function(info) {
[9cf7ff7b-b89a-4078-b020-7f2839402eca]     41:        if ("subtitle" in info.event.extendedProps) {
[9cf7ff7b-b89a-4078-b020-7f2839402eca]     42:          title = "<span class=\"fc-title\"><b>" + info.event.title + "</b> - " + info.event.extendedProps.subtitle + "</span>"
[9cf7ff7b-b89a-4078-b020-7f2839402eca]
[9cf7ff7b-b89a-4078-b020-7f2839402eca] /srv/webapps/fundaction_stage/shared/bundle/ruby/2.5.0/bundler/gems/decidim-module-calendar-dc07594b3004/app/helpers/decidim/calendar/calendar_helper.rb:23:in `calendar_event'srv/webapps/fundaction_stage/shared/bundle/ruby/2.5.0/bundler/gems/decidim-module-calendar-dc07594b3004/app/helpers/decidim/calendar/calendar_helper.rb:17:in `block in render_events'pps/fundaction_stage/shared/bundle/ruby/2.5.0/bundler/gems/decidim-module-calendar-dc07594b3004/app/helpers/decidim/calendar/calendar_helper.rb:17:in `collect'2eca] /srv/webapps/fundaction_stage/shared/bundle/ruby/2.5.0/bundler/gems/decidim-module-calendar-dc07594b3004/app/helpers/decidim/calendar/calendar_helper.rb:17:in `render_events'/srv/webapps/fundaction_stage/shared/bundle/ruby/2.5.0/bundler/gems/decidim-module-calendar-dc07594b3004/app/views/decidim/calendar/calendar/index.html.erb:39:in `__srv_webapps_fundaction_stage_shared_bundle_ruby_______bundler_gems_decidim_module_calendar_dc_____b_____app_views_decidim_calendar_calendar_index_html_erb___262886712440860621_46971431603340'pport (5.2.1.1) lib/active_support/notifications.rb:170:in `instrument'
[9cf7ff7b-b89a-4078-b020-7f2839402eca] actionview (5.2.1.1) lib/action_view/template.rb:354:in `instrument_render_template'
[9cf7ff7b-b89a-4078-b020-7f2839402eca] actionview (5.2.1.1) lib/action_view/template.rb:157:in `render'
~~~~

**Comment by mijailr** [comment]
Is possible, if there is any object in database incomplete with the necessary values will end in a similar issue. Have to dig in the database to fix any issue.

**Comment by mijailr** [comment]
Is wird because the decidim validations on models and views are preventing this type of issues. Do you make any changes in staging database using the rails console?

**Comment by jkraemer** [comment]
I'll see about giving you access to a dump of the DB. Since this DB is the result of real world usage, the code should be able to handle such nil values somehow I think...

**Pull request merged**
